<?php 
    return [

        ["nombre" => "PIZZA MARGARITA", 
        "imagen" => "margarita.jpg", 
            "ingrediente1" => "220 g. de masa de pizza italiana",
            "ingrediente2" => "90 g. de queso mozzarella",
            "ingrediente3" => "Hojas de albahaca fresca",   
            "ingrediente4" => "100 g. de salsa de tomate natural triturado",    
            "ingrediente5" => "Sal",  
            "ingrediente6" => "Una pizca de pimienta negra recién molida",   
            "ingrediente7" => "Aceite de oliva virgen extra",],

        ["nombre" => "PIZZA BARBACOA", 
        "imagen" => "barbacoa.jpg",
            "ingrediente1" => "Carne picada 125g",
            "ingrediente2" => "Masa de pizza 220g",
            "ingrediente3" => "Sofrito casero de tomate cuatro cucharadas sopera",   
            "ingrediente4" => "Pimiento verde italiano y oregano",    
            "ingrediente5" => "Mozzarella fresca abundante",  
            "ingrediente6" => "Salsa Barbacoa 3 cucharadas soperas",   
            "ingrediente7" => "Bacon picado en taquitos 80g",],

        ["nombre" => "PIZZA MARGARITA", 
        "imagen" => "margarita.jpg", 
            "ingrediente1" => "220 g. de masa de pizza italiana",
            "ingrediente2" => "90 g. de queso mozzarella",
            "ingrediente3" => "Hojas de albahaca fresca",   
            "ingrediente4" => "100 g. de salsa de tomate natural triturado",    
            "ingrediente5" => "Sal",  
            "ingrediente6" => "Una pizca de pimienta negra recién molida",   
            "ingrediente7" => "Aceite de oliva virgen extra",],
    
        ["nombre" => "PIZZA BARBACOA", 
        "imagen" => "barbacoa.jpg",
            "ingrediente1" => "Carne picada 125g",
            "ingrediente2" => "Masa de pizza 220g",
            "ingrediente3" => "Sofrito casero de tomate cuatro cucharadas sopera",   
            "ingrediente4" => "Pimiento verde italiano y oregano",    
            "ingrediente5" => "Mozzarella fresca abundante",  
            "ingrediente6" => "Salsa Barbacoa 3 cucharadas soperas",   
            "ingrediente7" => "Bacon picado en taquitos 80g",],

        ["nombre" => "PIZZA MARGARITA", 
        "imagen" => "margarita.jpg", 
            "ingrediente1" => "220 g. de masa de pizza italiana",
            "ingrediente2" => "90 g. de queso mozzarella",
            "ingrediente3" => "Hojas de albahaca fresca",   
            "ingrediente4" => "100 g. de salsa de tomate natural triturado",    
            "ingrediente5" => "Sal",  
            "ingrediente6" => "Una pizca de pimienta negra recién molida",   
            "ingrediente7" => "Aceite de oliva virgen extra",],

        ["nombre" => "PIZZA BARBACOA", 
        "imagen" => "barbacoa.jpg",
            "ingrediente1" => "Carne picada 125g",
            "ingrediente2" => "Masa de pizza 220g",
            "ingrediente3" => "Sofrito casero de tomate cuatro cucharadas sopera",   
            "ingrediente4" => "Pimiento verde italiano y oregano",    
            "ingrediente5" => "Mozzarella fresca abundante",  
            "ingrediente6" => "Salsa Barbacoa 3 cucharadas soperas",   
            "ingrediente7" => "Bacon picado en taquitos 80g",],
    ];
?>